# Generated by Django 4.2.3 on 2023-07-16 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='who_likes',
            field=models.ManyToManyField(related_name='whom_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
